OpsCMDB/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from Collect import views

urlpatterns = [
    # 加载上传资源
    # 使用re_path 支持正则表达式
    re_path('^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # path('admin/', admin.site.urls),
    path('rbac/', include('rbac.urls')),
    path('monitor/', include('monitor.urls')),
    path('index/', views.IndexView.as_view(), name='index')
]

rbac/urls.py
from django.urls import path
from rbac import views

app_name = 'rbac'
urlpatterns = [
    # 登陆/登出
    path('login.html', views.UserLoginView.as_view(), name='login'),
    path('logout.html', views.UserLogoutView.as_view(), name='logout'),
    # 用户管理
    path('user/list.html', views.UserListView.as_view(), name='users'),
    path('user/edit/<int:user_id>.html', views.UserEditView.as_view(), name='user_edit'),
    path('user/del/<int:user_id>.html', views.UserDelView.as_view(), name='user_delete'),
    path('user/add.html', views.UserRegisterView.as_view(), name='user_register'),
    path('user/password.html', views.CurrentUserPasswordReset.as_view(), name='password'),
    # 角色管理
    path('role/list.html', views.RoleListView.as_view(), name='roles'),
    path('role/add.html', views.RoleRegisterView.as_view(), name='roles_register'),
    path('role/del/<int:role_id>.html', views.RoleDelView.as_view(), name='roles_delete'),
    path('role/edit/<int:role_id>.html', views.RoleEditView.as_view(), name='roles_edit'),
    # 菜单管理
    path('menu/list.html', views.MenuListView.as_view(), name='menu'),
    path('menu/add.html', views.MenuRegisterView.as_view(), name="menu_register"),
    path('menu/del/<int:menu_id>.html', views.MenuDelView.as_view(), name="menu_delete"),
    path('menu/edit/<int:menu_id>.html', views.MenuEditView.as_view(), name="menu_edit"),
    # 权限管理
    path('permission/list.html', views.PermissionListView.as_view(), name="permission"),
    path('permission/add.html', views.PermissionRegisterView.as_view(), name="permission_register"),
    path('permission/del/<int:permission_id>.html', views.PermissionDelView.as_view(), name="permission_delete"),
    path('permission/edit/<int:permission_id>.html', views.PermissionEditView.as_view(), name="permission_edit"),
    # 权限组管理
    path('permission_group/list.html', views.PermissionGroupListView.as_view(), name='permission_group'),
    path('permission_group/add.html', views.PermissionGroupRegisterView.as_view(), name="permission_group_register"),
    path(
        'permission_group/edit/<int:group_id>.html',
        views.PermissionGroupEditView.as_view(),
        name='permission_group_update'
    ),
    path(
        'permission_group/del/<int:group_id>.html',
        views.PermissionGroupDelView.as_view(),
        name='permission_group_delete'
    ),
    # 部门管理
    path('department/list.html', views.DepartmentListView.as_view(), name='department'),
    path('department/add.html', views.DepartmentRegisterView.as_view(), name="department_register"),
    path('department/del/<int:department_id>.html', views.DepartmentDelView.as_view(), name="department_delete"),
    path('department/edit/<int:department_id>.html', views.DepartmentEditView.as_view(), name="department_edit")
]

rbac/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from .service.managers import UserManager
from django.utils import timezone


class UserInfo(AbstractBaseUser, PermissionsMixin):
    username = models.EmailField(_('邮件'), max_length=50, default='', unique=True)
    first_name = models.CharField(_('姓'), max_length=50, default='', blank=True, null=False)
    last_name = models.CharField(_('名'), max_length=50, default='')
    mobile = models.CharField(_("手机"), max_length=11, blank=True, null=True)
    img = models.ImageField(_("头像"), upload_to='static/img/users/',
                            default='/avatar/100_1.jpg', null=False, blank=False)
    department = models.ForeignKey('Department', verbose_name="部门", blank=True, on_delete=False)
    is_active = models.BooleanField(_("有效"), default=True)
    is_staff = models.BooleanField(_("员工"), default=True)
    create_date = models.DateTimeField(_('创建日期'), auto_now_add=True)
    roles = models.ManyToManyField(verbose_name='具有的所有角色', to="Role", blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'mobile', 'department', 'is_active', 'is_superuser']

    object = UserManager()

    class Meta:
        verbose_name_plural = _("User")

    def __str__(self):
        return self.username


class Role(models.Model):
    """
    角色表
   CEO
   CTO
   UFO
   销售主管
   销售员
    """
    title = models.CharField(verbose_name='角色名称', max_length=32, unique=True)
    permission = models.ManyToManyField(verbose_name='拥有权限', to="Permission")
    create_date = models.DateTimeField(_('创建日期'), auto_now_add=True)

    def __str__(self):
        return self.title


class Menu(models.Model):
    type_choice = {
        ("system", "系统菜单"),
        ("general", "一般菜单"),
        ("current", "当前用户")}
    name = models.CharField(verbose_name="菜单名称", max_length=32, unique=True)
    types = models.CharField(verbose_name="菜单种类", choices=type_choice, default="select", max_length=50)
    create_date = models.DateTimeField(_('创建日期'), auto_now_add=True)

    def __str__(self):
        return self.name


class PermissionGroup(models.Model):
    """
    权限组
   用户权限组
                用户列表
   主机权限组
                主机列表
    """
    name = models.CharField(max_length=32, unique=True)
    menu = models.ForeignKey(verbose_name='所属菜单', to='Menu', on_delete=False)
    create_date = models.DateTimeField(_('创建日期'), auto_now_add=True)

    def __str__(self):
        return self.name


class Permission(models.Model):
    """
    权限表
                                                                                组内菜单ID
    用户列表      /users/                 list               1            null
    添加用户      /users/add/             add                1            1
    删除用户      /users/del/(\d+)/       del                1            1
    修改用户      /users/edit/(\d+)/      edit               1            1
    主机列表      /hosts/                 list               2            null
    添加主机      /hosts/add/             add                2             5
    删除主机      /hosts/del/(\d+)/       del                2             5
    修改主机      /hosts/edit/(\d+)/      edit               2             5

    以后获取当前用户权限后，数据结构化处理，并放入session
    {
        1: {
            urls: [/users/,/users/add/ ,/users/del/(\d+)/],
            codes: [list,add,del]
        },
        2: {
            urls: [/hosts/,/hosts/add/ ,/hosts/del/(\d+)/],
            codes: [list,add,del]
        }
    }


    """
    code_choice = {
        ("insert", "添加"),
        ("delete", "删除"),
        ("select", "查看"),
        ("update", "修改")
    }
    title = models.CharField(verbose_name='权限名称', max_length=32, unique=True)
    code = models.CharField(verbose_name="读写情况", choices=code_choice, default="select", max_length=50)
    group = models.ForeignKey(verbose_name='所属权限组', to="PermissionGroup", on_delete=False)
    url = models.CharField(verbose_name='含正则的URL', max_length=255)
    # is_menu = models.BooleanField(verbose_name='是否是菜单')
    group_menu = models.ForeignKey(verbose_name='组内菜单', to="Permission", null=True, blank=True, related_name='权限',
                                   on_delete=False)
    create_date = models.DateTimeField(_('创建日期'), auto_now_add=True)

    def __str__(self):
        return self.title


class Department(models.Model):
    """
    部门
    """
    title = models.CharField(max_length=32, unique=True)
    create_date = models.DateTimeField(_(u'创建日期'), auto_now_add=True)

    def __str__(self):
        return self.title

rbac/forms.py
# -*- coding: utf-8 -*-
__author__ = 'YSQ'
from django import forms
from django.forms import Form, ModelForm
from django.forms import fields
from django.forms import widgets
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _
from .models import *


# 登陆form
class LoginForm(Form):
    username = fields.EmailField(
        label="用户名",
        required=True,
        error_messages={
            'required': '用户名不能为空',
        },
        widget=widgets.TextInput(attrs={'class': 'form-control m-input'})
    )
    password = fields.CharField(
        label='密码',
        required=True,
        error_messages={
            'required': '密码不能为空'
        },
        widget=widgets.PasswordInput(attrs={'class': 'form-control m-input'})
    )


# 修改密码
class PasswordReset(forms.Form):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'password_incorrect': _("Your old password was entered incorrectly. Please enter it again."),
    }
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True, 'class': 'form-control m-input'}),
        required=True,
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autofocus': True, 'class': 'form-control m-input'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
        required=True,
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True, 'class': 'form-control m-input'}),
        required=True,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


# 新增用户和修改用户
class UserProfixForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfixForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['username'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['mobile'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['department'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = UserInfo
        fields = ['username', 'first_name', 'last_name', 'mobile', 'img', 'department', 'is_active',
                  'is_staff', 'roles']
        widgets = {
            "roles": widgets.CheckboxSelectMultiple(
                attrs={"class": "form-control m-bootstrap-select m_selectpicker"}
            )
        }

    def save(self, commit=True, create=True):
        """
        :param commit:
        :param create:
        :return:
        """
        users = super(UserProfixForm, self).save(commit=True)
        if create:
            users.save()
        elif not create and commit:
            user_profile = UserInfo.objects.get(username=self.cleaned_data['username'])
            user_profile.save()
            user_profile.roles.set("")
            for role in self.cleaned_data['roles']:
                user_profile.roles.add(role)
        else:
            return users
        return users


# 角色修改和添加
class RoleInfoModelForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(RoleInfoModelForm, self).__init__(*args, **kwargs)
    #     self.fields['title'].widget.attrs.update({'class': 'form-control m-input'})
    #     self.fields['permissions'].widget.attrs.update({'class': 'form-control m-input'})

    def save(self, commit=True, create=True):
        """
        :param commit:
        :param create:
        :return:
        """
        role = super(RoleInfoModelForm, self).save(commit=True)
        if create and commit:
            role.save()
        elif not create and commit:
            role_profile = Role.objects.get(title=self.cleaned_data['title'])
            role_profile.save()
            role_profile.permission.set("")
            for permission in self.cleaned_data['permission']:
                role_profile.permission.add(permission.id)
        else:
            return role
        return role

    class Meta:
        model = Role
        fields = ("title", "permission")
        widgets = {
            "title": widgets.TextInput(attrs={"class": "form-control m-input"}),
            "permission": widgets.CheckboxSelectMultiple(
                attrs={"class": "form-control m-input"},
            )
        }

        labels = {
            "title": "角色名称",
            "permission": "权限",
        }


# 菜单修改和添加
class MenuInfoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MenuInfoForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['types'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = Menu
        fields = "__all__"
        exclude = ['create_date']


# 权限组修改和添加
class PermissionGroupForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PermissionGroupForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['menu'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = PermissionGroup
        fields = "__all__"
        exclude = ['create_date']


# 权限修改和添加
class PermissionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PermissionForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['url'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['code'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['group'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['group_menu'].widget.attrs.update({'class': 'form-control m-input'})

    def save(self, commit=True):
        permission = super(PermissionForm, self).save(commit=commit)
        permission.url = self.cleaned_data["url"] + ".html"
        if commit:
            permission.save()
        return permission

    class Meta:
        model = Permission
        fields = "__all__"
        exclude = ['create_date']


# 部门修改和添加
class DepartmentForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(DepartmentForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = Department
        fields = "__all__"
        exclude = ['create_date']
        labels = {
            "title": "部门"
        }

templates/rbac/menu_site.html
{% extends "sider.html" %}
{% load staticfiles %}
{% block head %}
    {% block title %}{{ view_message }} - 哆可梦运维管理系统{% endblock %}
{% endblock %}
{% block mainbody %}
    <!-- begin::Body -->
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
                <div class="m-subheader ">
                    <div class="d-flex align-items-center">
                        <div class="mr-auto">
                            <h3 class="m-subheader__title m-subheader__title--separator">{{ view_message }}</h3>
                            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                                <li class="m-nav__item m-nav__item--home">
                                    <a href="#" class="m-nav__link m-nav__link--icon">
                                        <i class="m-nav__link-icon la la-home"></i>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">用户列表</span>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">部门列表</span>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">权限列表</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

        <!-- END: Subheader -->
        <div class="m-content">
            <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30"
                 role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation m--font-brand"></i>
                </div>
                <div class="m-alert__text">
                    DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon
                    the foundations of progressive enhancement, and will add advanced interaction controls to any HTML
                    table. For more info see
                    <a href="https://datatables.net/"
                       target="_blank">the official home</a> of the plugin.
                </div>
            </div>
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {{ view_message }}
                            </h3>
                        </div>
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                            <li class="m-portlet__nav-item">
                                <a href="{% url 'rbac:menu_register' %}"
                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    <span>
                                        <i class="la la-plus"></i>
                                        <span>添加菜单</span>
                                    </span>
                                </a>
                            </li>
                            <li class="m-portlet__nav-item"></li>
{#                            <li class="m-portlet__nav-item">#}
{#                                <a href="#"#}
{#                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">#}
{#                                    <span>#}
{#                                        <i class="la la-male"></i>#}
{#                                        <span>删除角色</span>#}
{#                                    </span>#}
{#                                </a>#}
{#                            </li>#}
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">

                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>名称</th>
                            <th>菜单种类</th>
                            <th>创建时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if menu_data %}
                            {% for menu in menu_data %}
                                <td></td>
                                <td>{{ menu.name }}</td>
                                <td>{{ menu.get_types_display}}</td>
                                <td>{{ menu.create_date }}</td>
                                <td>
                                    <a href="{% url 'rbac:menu_edit' menu.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                    <a href="{% url 'rbac:menu_delete' menu.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la flaticon-delete-1"></i>
                                    </a>
                                </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- end:: Body -->
{% endblock %}
{% block script %}
    <!--begin::Page Snippets -->
    <script src="{% static 'js/datatables.bundle.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/role.js' %}" type="text/javascript"></script>
    <!--end::Page Snippets -->
{% endblock %}

templates/rbac/role.html
{% extends "sider.html" %}
{% load staticfiles %}
{% block head %}
    {% block title %}{{ view_message }} - 哆可梦运维管理系统{% endblock %}
{% endblock %}
{% block mainbody %}
    {% load rbac %}
    <!-- begin::Body -->
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">{{ view_message }}</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">用户列表</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">部门列表</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">权限列表</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
            <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30"
                 role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation m--font-brand"></i>
                </div>
                <div class="m-alert__text">
                    DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon
                    the foundations of progressive enhancement, and will add advanced interaction controls to any HTML
                    table. For more info see
                    <a href="https://datatables.net/"
                       target="_blank">the official home</a> of the plugin.
                </div>
            </div>
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {{ view_message }}
                            </h3>
                        </div>
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                            <li class="m-portlet__nav-item">
                                <a href="{% url 'rbac:roles_register' %}"
                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    <span>
                                        <i class="la la-plus"></i>
                                        <span>添加角色</span>
                                    </span>
                                </a>
                            </li>
                            <li class="m-portlet__nav-item"></li>
                            {#                            <li class="m-portlet__nav-item">#}
                            {#                                <a href="#"#}
                            {#                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">#}
                            {#                                    <span>#}
                            {#                                        <i class="la la-male"></i>#}
                            {#                                        <span>删除角色</span>#}
                            {#                                    </span>#}
                            {#                                </a>#}
                            {#                            </li>#}
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">

                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>名称</th>
                            <th>关联权限</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if role_list %}
                            {% for role in role_list %}
                                <td></td>
                                <td>{{ role.title }}</td>
                                <td>
                                    {% for per in role.permission.all %}
                                        <a href="#" class="btn btn-{{ forloop.counter0|get_index }}">
                                            {{ per.title }}:{{ per.get_code_display  }}
                                        </a>
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'rbac:roles_edit' role.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only
                                    m-btn--pill"
                                       title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                    <a href="{% url 'rbac:roles_delete' role.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la flaticon-delete-1"></i>
                                    </a>
                                </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- end:: Body -->
{% endblock %}
{% block script %}
    <!--begin::Page Snippets -->
    <script src="{% static 'js/datatables.bundle.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/role.js' %}" type="text/javascript"></script>
    <!--end::Page Snippets -->
{% endblock %}