OpsCMDB/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from Collect import views

urlpatterns = [
    # 加载上传资源
    # 使用re_path 支持正则表达式
    re_path('^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # path('admin/', admin.site.urls),
    path('rbac/', include('rbac.urls')),
    path('monitor/', include('monitor.urls')),
    path('index/', views.IndexView.as_view(), name='index')
]

monitor/urls.py
from django.urls import path
from monitor import views

app_name = 'monitor'
urlpatterns = [
    # 监控信息管理
    path('permit/list.html', views.MonitorListView.as_view(), name='information_list'),
    path('permit/add.html', views.MonitorAddView.as_view(), name="information_add"),
    path('permit/del/<int:monitor_id>.html', views.MonitorDelView.as_view(), name="information_del"),
    path('permit/edit/<int:monitor_id>.html', views.MonitorEditView.as_view(), name="information_edit"),
    # 报警消息管理
    path('prometheus/alert.html', views.AlertPrometheusListView.as_view(), name="alert_prometheus"),
    # 发送消息管理
    path('alert/list.html', views.AlertPrometheusListView.as_view(), name="alert_list"),
    # 报警规则
    path('rule/list.html', views.ContactRuleListView.as_view(), name='rule_list'),
    path('rule/add.html', views.ContactRuleAddView.as_view(), name="rule_add"),
    path('rule/del/<int:rule_id>.html', views.ContactRuleDelView.as_view(), name="rule_del"),
    path('rule/edit/<int:rule_id>.html', views.ContactRuleEditView.as_view(), name="rule_edit"),
    # 报警联系人
    path('user/list.html', views.ContactUserListView.as_view(), name='user_list'),
    path('user/add.html', views.ContactUserAddView.as_view(), name="user_add"),
    path('user/del/<int:user_id>.html', views.ContactUserDelView.as_view(), name="user_del"),
    path('user/edit/<int:user_id>.html', views.ContactUserEditView.as_view(), name="user_edit"),
    # 报警联系人组
    path('group/list.html', views.ContactGroupListView.as_view(), name='group_list'),
    path('group/add.html', views.ContactGroupAddView.as_view(), name="group_add"),
    path('group/del/<int:group_id>.html', views.ContactGroupDelView.as_view(), name="group_del"),
    path('group/edit/<int:group_id>.html', views.ContactGroupEditView.as_view(), name="group_edit"),
]

rbac/urls.py
from django.urls import path
from rbac import views

app_name = 'rbac'
urlpatterns = [
    # 登陆/登出
    path('login.html', views.UserLoginView.as_view(), name='login'),
    path('logout.html', views.UserLogoutView.as_view(), name='logout'),
    # 用户管理
    path('user/list.html', views.UserListView.as_view(), name='users'),
    path('user/edit/<int:user_id>.html', views.UserEditView.as_view(), name='user_edit'),
    path('user/del/<int:user_id>.html', views.UserDelView.as_view(), name='user_delete'),
    path('user/add.html', views.UserRegisterView.as_view(), name='user_register'),
    path('user/password.html', views.CurrentUserPasswordReset.as_view(), name='password'),
    # 角色管理
    path('role/list.html', views.RoleListView.as_view(), name='roles'),
    path('role/add.html', views.RoleRegisterView.as_view(), name='roles_register'),
    path('role/del/<int:role_id>.html', views.RoleDelView.as_view(), name='roles_delete'),
    path('role/edit/<int:role_id>.html', views.RoleEditView.as_view(), name='roles_edit'),
    # 菜单管理
    path('menu/list.html', views.MenuListView.as_view(), name='menu'),
    path('menu/add.html', views.MenuRegisterView.as_view(), name="menu_register"),
    path('menu/del/<int:menu_id>.html', views.MenuDelView.as_view(), name="menu_delete"),
    path('menu/edit/<int:menu_id>.html', views.MenuEditView.as_view(), name="menu_edit"),
    # 权限管理
    path('permission/list.html', views.PermissionListView.as_view(), name="permission"),
    path('permission/add.html', views.PermissionRegisterView.as_view(), name="permission_register"),
    path('permission/del/<int:permission_id>.html', views.PermissionDelView.as_view(), name="permission_delete"),
    path('permission/edit/<int:permission_id>.html', views.PermissionEditView.as_view(), name="permission_edit"),
    # 权限组管理
    path('permission_group/list.html', views.PermissionGroupListView.as_view(), name='permission_group'),
    path('permission_group/add.html', views.PermissionGroupRegisterView.as_view(), name="permission_group_register"),
    path(
        'permission_group/edit/<int:group_id>.html',
        views.PermissionGroupEditView.as_view(),
        name='permission_group_update'
    ),
    path(
        'permission_group/del/<int:group_id>.html',
        views.PermissionGroupDelView.as_view(),
        name='permission_group_delete'
    ),
    # 部门管理
    path('department/list.html', views.DepartmentListView.as_view(), name='department'),
    path('department/add.html', views.DepartmentRegisterView.as_view(), name="department_register"),
    path('department/del/<int:department_id>.html', views.DepartmentDelView.as_view(), name="department_delete"),
    path('department/edit/<int:department_id>.html', views.DepartmentEditView.as_view(), name="department_edit")
]

monitor/models.py
import uuid

from django.db import models

from rbac.models import UserInfo


# Create your models here.

class MonitorAccount(models.Model):
    monitor_choice = {
        ('ZABBIX', 'ZABBIX'),
        ('PROMETHEUS', '普罗米修斯'),
        ('CONSUL', 'Consul')
    }
    request_choice = {
        ('http', 'http'),
        ('https', 'https')
    }
    title = models.CharField(verbose_name='报警名称', max_length=64)
    secret_id = models.CharField(verbose_name='监控用户', max_length=64)
    secret_key = models.CharField(verbose_name='监控密码', max_length=64)
    host = models.GenericIPAddressField(verbose_name="监控IP")
    port = models.IntegerField(verbose_name="监控端口")
    monitor_type = models.CharField(verbose_name='监控类型', choices=monitor_choice, max_length=64)
    request_type = models.CharField(verbose_name="请求方式", choices=request_choice, max_length=6)
    create_user = models.CharField(verbose_name='监控用户', max_length=50)
    create_date = models.DateTimeField(verbose_name='创建日期', auto_now_add=True)

    class Meta:
        verbose_name_plural = "监控系统信息"


class AlertPrometheus(models.Model):
    alert_status = {
        ('firing', '报警中'),
        ('resolved', '已解决')
    }
    event_id = models.UUIDField(verbose_name="动作id", default=uuid.uuid3(uuid.NAMESPACE_DNS, "Alert"), unique=True)
    status = models.CharField(verbose_name='状态', max_length=64, default='firing', choices=alert_status)
    labels = models.TextField(verbose_name="资源信息", default=None, max_length=500)
    annotations = models.TextField(verbose_name="报警内容", default=None, max_length=500)
    startsAt = models.DateTimeField(verbose_name='开始报警时间')
    endsAt = models.DateTimeField(verbose_name='结束报警时间')
    generatorURL = models.URLField(verbose_name="产生报警URL", max_length=300)
    record_time = models.DateTimeField(verbose_name='记录报警时间', auto_now_add=True)

    class Meta:
        index_together = ["event_id"]
        verbose_name_plural = "普罗米修斯报警汇总"


class AlertFormat(models.Model):
    status_choice = {
        ("firing", "报警中"),
        ("resolved", "已解决"),
    }
    alertname = models.CharField(verbose_name="报警项", max_length=20, default=None)
    contact_rule = models.ForeignKey(verbose_name="报警规则", to="ContactRule", on_delete=False, default=None)
    status = models.CharField(verbose_name="发送状态", choices=status_choice, max_length=10, default="firing")
    job = models.CharField(verbose_name="主机组", max_length=20, default=None)
    instance = models.CharField(verbose_name="数据源", max_length=20, default=None)
    project = models.CharField(verbose_name="数据源", max_length=20, default=None)
    severity = models.CharField(verbose_name="报警等级", max_length=20, default=None)
    tag = models.TextField(verbose_name="报警备注", max_length=2000, default="")
    description = models.TextField(verbose_name="报警描述", max_length=5000, default=None)
    startsAt = models.DateTimeField(verbose_name="变更时间")

    class Meta:
        verbose_name_plural = "报警汇总消息"
        index_together = ['job', 'severity']


class AlertMessage(models.Model):
    status_choice = {
        (1, "已发送"),
        (2, "未发送"),
        (3, "发送失败")
    }
    status = models.IntegerField(verbose_name="发送状态", choices=status_choice)
    contact_user = models.ForeignKey(verbose_name="接收人", on_delete=False, to="ContactUser", default=None)
    message = models.TextField(verbose_name="发送消息内容", max_length=2000, default="")
    startsAt = models.DateTimeField(verbose_name="变更时间", auto_now_add=True)

    class Meta:
        verbose_name_plural = "报警消息发送状态"


class ContactUser(models.Model):
    choice = {
        ("Wechat", "微信"),
        ("Voice", "电话"),
        ("Sms", "短信"),
        ("Email", "邮件")
    }
    contact_user = models.ForeignKey(verbose_name="用户ID", to=UserInfo, on_delete=False, default=None)
    contact_address = models.CharField(verbose_name="接收地址", max_length=200, default=None)
    contact_group = models.ForeignKey(verbose_name="发送规则组", to="ContactGroup", default=None, on_delete=False)
    contact_level = models.IntegerField(verbose_name="发送优先级(数字)", default=0)
    contact_type = models.CharField(verbose_name="接收类型", choices=choice, max_length=10, default="Voice")
    create_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)

    class Meta:
        verbose_name_plural = "发送联系人"
        unique_together = ['contact_user', 'contact_type']


class ContactGroup(models.Model):
    contact_choice = {
        ("VoiceMessage", "语音"),
        ("SmsMessage", "短信"),
        ("EmailMessage", "邮件"),
        ("WechatMessage", "微信")
    }
    group_name = models.CharField(verbose_name="联系组名", max_length=50, default=None)
    contact_type = models.CharField(verbose_name="消息方法", choices=contact_choice, default=None, max_length=20)
    create_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)

    def __str__(self):
        return "%s--%s" % (self.group_name, self.contact_type)


class ContactRule(models.Model):
    rule_choice = {
        ("Level1", "严重"),
        ("Level2", "一般"),
        ("Level3", "普通"),
    }
    rule_name = models.CharField(verbose_name="规则名称", max_length=40, default=None)
    regex_rule = models.CharField(verbose_name="匹配规则", max_length=60, default=None)
    contact_group = models.ForeignKey(verbose_name="发送规则组", to=ContactGroup, default=None, on_delete=False)
    severity = models.CharField(verbose_name="报警等级", max_length=20, choices=rule_choice, default=None)
    create_time = models.DateTimeField(verbose_name="添加时间", auto_now_add=True)

    def __str__(self):
        return self.rule_name

    class Meta:
        verbose_name_plural = "发送规则"
        unique_together = ['regex_rule', 'severity', 'contact_group']

monitor/forms.py
# -*- coding: utf-8 -*-
__author__ = 'YSQ'
from django import forms
from django.forms import Form, ModelForm
from django.forms import fields
from django.forms import widgets

from .models import *


class MonitorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MonitorForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['secret_id'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['host'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['port'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['monitor_type'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['request_type'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = MonitorAccount
        fields = '__all__'
        exclude = ['create_date', 'create_user']
        widgets = {
            "secret_key": widgets.PasswordInput(attrs={"class": "form-control m-input"})
        }


class ContactRuleForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactRuleForm, self).__init__(*args, **kwargs)
        self.fields['rule_name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['regex_rule'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_group'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['severity'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = ContactRule
        exclude = ['create_time', 'create_user']


class ContactUserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactUserForm, self).__init__(*args, **kwargs)
        self.fields['contact_user'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_address'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_group'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_level'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_type'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = ContactUser
        exclude = ['create_time', 'create_user']
        widgets = {
            "contact_rule": widgets.CheckboxSelectMultiple(
                attrs={"class": "form-control m-bootstrap-select m_selectpicker"}
            )
        }


class ContactGroupForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactGroupForm, self).__init__(*args, **kwargs)
        self.fields['group_name'].widget.attrs.update({'class': 'form-control m-input'})
        self.fields['contact_type'].widget.attrs.update({'class': 'form-control m-input'})

    class Meta:
        model = ContactGroup
        exclude = ['create_time']

templates/monitor/contact_user.html
{% extends "sider.html" %}
{% load staticfiles %}
{% block head %}
    {% block title %}{{ view_message }} - 哆可梦运维管理系统{% endblock %}
{% endblock %}
{% block mainbody %}
    <!-- begin::Body -->
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">{{ view_message }}</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">用户列表</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">部门列表</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">权限列表</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
            <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30"
                 role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation m--font-brand"></i>
                </div>
                <div class="m-alert__text">
                    DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon
                    the foundations of progressive enhancement, and will add advanced interaction controls to any HTML
                    table. For more info see
                    <a href="https://datatables.net/"
                       target="_blank">the official home</a> of the plugin.
                </div>
            </div>
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {{ view_message }}
                            </h3>
                        </div>
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                            <li class="m-portlet__nav-item">
                                <a href="{% url 'monitor:user_add' %}"
                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    <span>
                                        <i class="la la-plus"></i>
                                        <span>添加信息</span>
                                    </span>
                                </a>
                            </li>
                            <li class="m-portlet__nav-item"></li>
                            {#                            <li class="m-portlet__nav-item">#}
                            {#                                <a href="#"#}
                            {#                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">#}
                            {#                                    <span>#}
                            {#                                        <i class="la la-male"></i>#}
                            {#                                        <span>删除角色</span>#}
                            {#                                    </span>#}
                            {#                                </a>#}
                            {#                            </li>#}
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">

                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>联系人账户名</th>
                            <th>联系地址</th>
                            <th>联系人分组</th>
                            <th>报警类型</th>
                            <th>添加时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if contact_data %}
                            {% for contact in contact_data %}
                                <td></td>
                                <td>{{ contact.contact_user }}</td>
                                <td>{{ contact.contact_address }}</td>
                                <td>{{ contact.contact_group }}</td>
{#                                {% for role in contact.contact_rule.all %}#}
{#                                        <a href="{% url 'monitor:rule_list' %}">#}
{#                                            {{ role.rule_name }}#}
{#                                        </a>#}
{#                                    {% endfor %}#}
{#                                </td>#}
                                <td>{{ contact.get_contact_type_display }}</td>
                                <td>{{ contact.create_time }}</td>
                                <td>
                                    <a href="{% url 'monitor:user_edit' contact.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                    <a href="{% url 'monitor:user_del' contact.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la flaticon-delete-1"></i>
                                    </a>
                                </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- end:: Body -->
{% endblock %}
{% block script %}
    <!--begin::Page Snippets -->
    <script src="{% static 'js/datatables.bundle.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/role.js' %}" type="text/javascript"></script>
    <!--end::Page Snippets -->
{% endblock %}

templates/monitor/monitor.html
{% extends "sider.html" %}
{% load staticfiles %}
{% block head %}
    {% block title %}{{ view_message }} - 哆可梦运维管理系统{% endblock %}
{% endblock %}
{% block mainbody %}
    <!-- begin::Body -->
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
                <div class="m-subheader ">
                    <div class="d-flex align-items-center">
                        <div class="mr-auto">
                            <h3 class="m-subheader__title m-subheader__title--separator">{{ view_message }}</h3>
                            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                                <li class="m-nav__item m-nav__item--home">
                                    <a href="#" class="m-nav__link m-nav__link--icon">
                                        <i class="m-nav__link-icon la la-home"></i>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">用户列表</span>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">部门列表</span>
                                    </a>
                                </li>
                                <li class="m-nav__separator">-</li>
                                <li class="m-nav__item">
                                    <a href="" class="m-nav__link">
                                        <span class="m-nav__link-text">权限列表</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

        <!-- END: Subheader -->
        <div class="m-content">
            <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30"
                 role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation m--font-brand"></i>
                </div>
                <div class="m-alert__text">
                    DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon
                    the foundations of progressive enhancement, and will add advanced interaction controls to any HTML
                    table. For more info see
                    <a href="https://datatables.net/"
                       target="_blank">the official home</a> of the plugin.
                </div>
            </div>
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                {{ view_message }}
                            </h3>
                        </div>
                    </div>
                    <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                            <li class="m-portlet__nav-item">
                                <a href="{% url 'monitor:information_add' %}"
                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    <span>
                                        <i class="la la-plus"></i>
                                        <span>添加信息</span>
                                    </span>
                                </a>
                            </li>
                            <li class="m-portlet__nav-item"></li>
{#                            <li class="m-portlet__nav-item">#}
{#                                <a href="#"#}
{#                                   class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">#}
{#                                    <span>#}
{#                                        <i class="la la-male"></i>#}
{#                                        <span>删除角色</span>#}
{#                                    </span>#}
{#                                </a>#}
{#                            </li>#}
                        </ul>
                    </div>
                </div>
                <div class="m-portlet__body">

                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>报警名称</th>
                            <th>用户名</th>
                            <th>IP</th>
                            <th>端口</th>
                            <th>监控类型</th>
                            <th>请求方式</th>
                            <th>创建日期</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if monitor_data %}
                            {% for monitor in monitor_data %}
                                <td></td>
                                <td>{{ monitor.title }}</td>
                                <td>{{ monitor.secret_id }}</td>
                                <td>{{ monitor.host }}</td>
                                <td>{{ monitor.port }}</td>
                                <td>{{ monitor.get_monitor_type_display}}</td>
                                <td>{{ monitor.get_request_type_display}}</td>
                                <td>{{ monitor.create_date }}</td>
                                <td>
                                    <a href="{% url 'monitor:information_edit' monitor.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                    <a href="{% url 'monitor:information_del' monitor.pk %}"
                                       class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill"
                                       title="View">
                                        <i class="la flaticon-delete-1"></i>
                                    </a>
                                </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <!-- end:: Body -->
{% endblock %}
{% block script %}
    <!--begin::Page Snippets -->
    <script src="{% static 'js/datatables.bundle.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/role.js' %}" type="text/javascript"></script>
    <!--end::Page Snippets -->
{% endblock %}